In [6]:
def position_input():

    while True:

        try:

            user_input = [float(coordinate) for coordinate in input("Enter the coordinates: ").split()]

        except:
            
            print("Invalid input!")

        else:

            break


    match len(user_input):

        case 1:

            return np.array([0, 0] + user_input)

        case 2:

            return np.array(user_input + [0])

        case 3: 

            return np.array(user_input)

        case _:

            return 

In [56]:
import numpy as np
import matplotlib.pyplot as pl
import scipy.optimize as op
import scipy.constants as cn
from numpy.linalg import norm

WEIGHT = 1

def statics(T, *args):

    position, motors = args
    T = np.array(T)
    a = np.fromfunction(np.vectorize(lambda i, j: (motors[j][i] - position[i]) / norm(motors[i] - position)), (3, 4), dtype = int)
    return a.dot(T) + np.array([0, 0, - WEIGHT])

position = np.array([2, 0.19, 5])
motors = np.array([[0, -11.275, 10], [0, 4.678, 10], [6.01, 7.165, 10], [2.891, 3.663, 35]])

def tensions(motors, position):
    T = op.minimize(lambda T, *args: sum(list(T)), 
                x0 = [0, 0, 0, 0],
                args = (position, motors),
                bounds = ((0, None), ) * 4,
                constraints = [{"type": "eq", "fun": statics, 'args': (position, motors)}])
    return T.x

print(tensions(motors, position))

[1.00827676e-01 3.01181560e-02 2.15105711e-16 2.93930039e-01]


In [74]:
STEP_SIZE = 1/12
start = np.array([1, 1, 1])
stop = np.array([1, 2, 2])

num_steps = round(norm(stop - start) / STEP_SIZE)
steps = np.arange(num_steps)    # the different positions that are reached

trajectory = []
distance = stop - start

for step in range(num_steps):
    point = start + distance / norm(distance) * step
    trajectory.append(point)

x, y, z = ([],[],[] for i in rang)

[[ 1.          1.          1.        ]
 [ 1.          1.70710678  1.70710678]
 [ 1.          2.41421356  2.41421356]
 [ 1.          3.12132034  3.12132034]
 [ 1.          3.82842712  3.82842712]
 [ 1.          4.53553391  4.53553391]
 [ 1.          5.24264069  5.24264069]
 [ 1.          5.94974747  5.94974747]
 [ 1.          6.65685425  6.65685425]
 [ 1.          7.36396103  7.36396103]
 [ 1.          8.07106781  8.07106781]
 [ 1.          8.77817459  8.77817459]
 [ 1.          9.48528137  9.48528137]
 [ 1.         10.19238816 10.19238816]
 [ 1.         10.89949494 10.89949494]
 [ 1.         11.60660172 11.60660172]
 [ 1.         12.3137085  12.3137085 ]]


In [ ]:
start = np.array()
stop = np.array()

for 